# Generated by Django 4.1.7 on 2023-07-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slickmart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="Not defined", max_length=100),
            preserve_default=False,
        ),
    ]
